### PR TITLE
update to use mda >=0.11.0 API (fixes #2)

### LINKED ISSUE #2: update to work with MDAnalysis 0.11.0
The new MDAnalysis 0.11.0 release breaks the API and RotamerConvolveMD should be adapted accordingly; see the [0.11.0 release guide](https://github.com/MDAnalysis/mdanalysis/wiki/MDAnalysis-0.11-unifying-release-user-guide) (and in particular [migrating with ten2eleven.py](https://github.com/MDAnalysis/mdanalysis/wiki/Migrating-MDAnalysis-code-with-ten2eleven.py).

### PR DESCRIPTION
**Pull request by kain88-de**
This gets the example running and finishing. The resulting probability
density is a little bit different tough. 
- [reference.pdf](https://github.com/MDAnalysis/RotamerConvolveMD/files/232130/reference.pdf)
- [new.pdf](https://github.com/MDAnalysis/RotamerConvolveMD/files/232132/new.pdf)

The most likely explanation I have for that is that we now do a slightly different neighborsearch.

Fixes #2

### CODE REVIEW

**Comment by kain88-de** [comment]
ping @philipwfowler

**Comment by orbeckst** [comment]
@kain88-de thanks for looking at it! Did you run `ten2eleven`?

Btw, you can also ask Lukas :-) (not sure if he's on GitHub).

**Comment by orbeckst** [comment]
For reference: the code for the [KDTree.NeighborSearch.AtomNeighborSearch.search_list()](https://github.com/MDAnalysis/mdanalysis/blob/06c93bc0f6e664232e6ccbe401efc2ae02167e32/package/MDAnalysis/KDTree/NeighborSearch.py#L213) function.

**Comment by orbeckst** [comment]
I attached the figures from your email --- I hadn't seen them at first.

Qualitatively, the distributions look similar but I'd like to know why they are different at all.

**Comment by orbeckst** [comment]
Alternative explanation for the small differences: An important step in rotcon is to fit the spin label to the sidechain to "virtually" attach it, so clearly everything depends on this step. Didn't we change slightly the way that RMS-fitting was done, namely how/when mass weighting was done? That might also explain small differences in distribution.

**Comment by kain88-de** [comment]
So I did some tests. This package work perfectly with 0.10.0. As soon as I switch to 0.11.0 it breaks. This will involve some more careful analysis.

Otherwise I didn't use `ten2eleven` yet. I'll update that soon.

**Comment by orbeckst** [comment]
@philipwfowler did you have a chance to look at the spin label distance distributions at the top of this issue? What kind of differences would you consider significant?

**Comment by kain88-de** [comment]
Ok found the error. It is a problem with the indices of the trajectory. In mda 0.11.0 we switched form 1 to 0 based indexing. That messes stuff up. I'm not yet sure how to fix this in `find_clashing_rotamers`

**Comment by kain88-de** [comment]
Hm strange @philipwfowler after looking at the code closer I think your original version has a bug.

The `rotamer_clash` list is 0-indexed. When you do a comparison [here](https://github.com/MDAnalysis/RotamerConvolveMD/blob/74b1d13495dfd5273608f63eb8014be90f72f8e9/rotcon/convolve.py#L122) using a TimeStep frame that is still 1-indexed in 0.10.0. By that you are off one frame in the original code.

So if anything my adopted version for 0.11.0 is correct. So until @philipwfowler had a look over the original code I suggest not to merge this.

**Comment by kain88-de** [comment]
If I fix the indexing on both lines I get the same result in the original version as I get with this updated branch.

**Comment by orbeckst** [comment]
For some reason, the rotamer library really starts at frame 1 (≥0.11 indexing), as implied by [my comment in library.RotamerLibrary.read_rotamer_weights()](https://github.com/MDAnalysis/RotamerConvolveMD/blob/74b1d13495dfd5273608f63eb8014be90f72f8e9/rotcon/library.py#L114). Consistent with `read_rotamer_weights()`, the  [rotamer_clash](https://github.com/MDAnalysis/RotamerConvolveMD/blob/74b1d13495dfd5273608f63eb8014be90f72f8e9/rotcon/convolve.py#L207) list also always contains `True` as the first element and the first real clash assessment is `rotamer_clash[1]`.

Therefore, I _think_ it should be 

``` python
if rotamer1.frame > 0 and not rotamer1_clash[rotamer1.frame]: 
# ...
if rotamer2.frame >  0 and not rotamer2_clash[rotamer2.frame]:
```

**Comment by katrinr** [comment]
Max and me tested the following change in the code and obtained a much better result. Only few steric clashes can be observed, but is still not the same result as shown in the reference.pdf (attached by Max).
Thanks a lot in advance!

``` python
if rotamer1.frame > 0 and not rotamer1_clash[rotamer1.frame + 1]: 
#   ...
if rotamer2.frame >  0 and not rotamer2_clash[rotamer2.frame + 1]:
```

peptso2

**Comment by orbeckst** [comment]
I don't understand why `[rotamer1.frame + 1]`... waiting for @philipwfowler to shed some light on things.

**Comment by philipwfowler** [comment]
Ok, I've gone back and looked at my original code before it was objectized. The "1"s all come from the fact that MDA trajectories used to 1-based (i.e. we are dealing with several Universes where we have to load in a PDB file first which used to be stored as frame 0 so we can load in either an `XYZ` or a `DCD` file). So the rotamer library is stored as a `XYZ`, so when you load it in it effectively becomes 1-based as we want to ignore the first `[0]` frame. Likewise the fitting procedure used `rms_fit_trj`. So, yes, I think there is a bug in the original code and it should read 

```
# only proceed if it isn't the PDB frame and there is no clash  
if rotamer1.frame > 0 and not rotamer1_clash[rotamer1.frame]:
```

`rotamer1_clash` in the original code is a list of Booleans created again assuming 1-based trajectories. The first one i.e. [0] is set to True as this again is the PDB being used to read in the fitted DCD. So the above code should be correct for 1-based trajectories.

Shifting to 0-based trajectories requires that we don't set the [first element of rotamer1_clash to be True](https://github.com/MDAnalysis/RotamerConvolveMD/blob/74b1d13495dfd5273608f63eb8014be90f72f8e9/rotcon/convolve.py#L207) and instead have

```
        rotamer_clash = []
```

Then the logic above can be simplified to

```
# only proceed if there is no clash 
if not rotamer1_clash[rotamer1.frame]:
```

since we don't have to exclude the PDB frame as the trajectories are now 0-based.

I suspect the rotamer1_clash was still be initialised with [True] which would have meant you'd have needed to shift the frames along by one, hence rotamer1.frame + 1 working.

I didn't understand what @orbeckst meant by the rotamer trajectories being 1-based even in newer versions of MDA. In my old code they are read in as a DCD so should now be 0-based. I did have them also stored as an XYZ frame which has manual "frame" labels and these do start at 1, but I think MDA is using the DCD not the XYZ.

**Comment by kain88-de** [comment]
@philipwfowler thanks that clarifies things.

**Comment by kain88-de** [comment]
the test script passes now.

**Comment by orbeckst** [comment]
> the test script passes now.

Were the tests generated with a "good" version of the code?

**Comment by kain88-de** [comment]
Yes. The bug we found wasn't affecting the tests because there wasn't a clash on the first frame. But @katrinr is spending some time on this right now anyway. I'll ask here to check if she can still find overlaps.

**Comment by orbeckst** [comment]
@philipwfowler said:

> I didn't understand what @orbeckst meant by the rotamer trajectories being 1-based even in newer versions of MDA. In my old code they are read in as a DCD so should now be 0-based. I did have them also stored as an XYZ frame which has manual "frame" labels and these do start at 1, but I think MDA is using the DCD not the XYZ.

I think I went of off your original code where I understood that the first rotamer would be at "`ts.frame == 2` (old MDA)" = "`ts.frame == 1` (new MDA)" = "`u.trajectory[1]`" (all MDA). This seems to have come from the assumption that when you load

``` python
u = Universe(PDB, DCD)
```

that the very first set of coordinates comes from the PDB and additional ones are appended (at least that's how I am interpreting your https://github.com/MDAnalysis/RotamerConvolveMD/pull/3#issuecomment-217295185 i.e. you assume that the total `len(u.trajectory) == "len(DCD)" + 1`. (This is how VMD handles things.) However, MDAnalysis never did that. When we use a PDB as a topology, we _only_ use atom type information, not the coordinates.

Looking at the weights in [data/R1A_298K_populations.dat](https://github.com/MDAnalysis/RotamerConvolveMD/blob/master/rotcon/data/R1A_298K_populations.dat) it's clear that frame 0 (new MDA from now on) is part of the library. Therefore, I am wondering if there's always been a bug in the code at least in the sense that we always skipped one rotamer (the first one)?

**Comment by kain88-de** [comment]
@orbeckst yes this bug existed in the old code, we always skipped the first rotamer.

**Comment by orbeckst** [comment]
Ok, opened #6. Reference it when you close it in a commit/PR.

**Comment by orbeckst** [comment]
This PR reproduces the test case and is compatible with MDAnalysis ≥0.11.0.
I will therefore merge it.

Note that there's still the question regarding weights #6 but that is independent from this PR.

**Pull request merged**
